### ISSUE TITLE
Manual version number

### ISSUE THREAD

**Issue by fnordahl** [openstack-charmers/snap-node-cert-exporter#3]
In the current version of the snap, the version is set manually and oddly used as a git branch/tag:
https://github.com/openstack-charmers/snap-node-cert-exporter/blob/3bae7e5d9491482a2984957c0fbc92059bb5de8c/snap/snapcraft.yaml#L27

I would expect this to be reversed, so that you specify the git tag and then use a programmatic approach to determine the version number for the snap.

Something like:
```yaml
adopt-info: node-cert-exporter

parts:
  node-cert-exporter:
    source-branch: the-branch-I-want-to-track
    override-stage: |
      craftctl set version ...
      craftctl default
```

There is an example of this in use here:
https://github.com/canonical/snap-ovn-chassis/blob/32d75e4a1ad7d23df50dd04fe4221f419f64db5f/snap/snapcraft.yaml#L226-L228
